/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.datamachines.kafka.converter.msgpack;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testFoo() {
        assertEquals(1, 1);
    }
}
